/**
 * 英語読み上げクリップのマニフェスト。scripts/generate-voice.mjs が自動生成する（手で編集しない）。
 * キー=英語トークン（小文字） → public/assets/voice/ 内のファイル名。
 * 空のときは Web Speech API（en-US）にフォールバックする。
 */
export const EN_VOICE_CLIPS: Record<string, string> = {
  "a": "en-a.mp3",
  "b": "en-b.mp3",
  "c": "en-c.mp3",
  "d": "en-d.mp3",
  "e": "en-e.mp3",
  "f": "en-f.mp3",
  "g": "en-g.mp3",
  "h": "en-h.mp3",
  "i": "en-i.mp3",
  "j": "en-j.mp3",
  "k": "en-k.mp3",
  "l": "en-l.mp3",
  "m": "en-m.mp3",
  "n": "en-n.mp3",
  "o": "en-o.mp3",
  "p": "en-p.mp3",
  "q": "en-q.mp3",
  "r": "en-r.mp3",
  "s": "en-s.mp3",
  "t": "en-t.mp3",
  "u": "en-u.mp3",
  "v": "en-v.mp3",
  "w": "en-w.mp3",
  "x": "en-x.mp3",
  "y": "en-y.mp3",
  "z": "en-z.mp3",
  "dog": "en-dog.mp3",
  "cat": "en-cat.mp3",
  "run": "en-run.mp3",
  "was": "en-was.mp3",
  "sun": "en-sun.mp3",
  "red": "en-red.mp3",
  "big": "en-big.mp3",
  "cup": "en-cup.mp3",
  "fish": "en-fish.mp3",
  "blue": "en-blue.mp3",
  "jump": "en-jump.mp3",
  "milk": "en-milk.mp3",
  "star": "en-star.mp3",
  "frog": "en-frog.mp3",
  "cake": "en-cake.mp3",
  "bird": "en-bird.mp3",
  "apple": "en-apple.mp3",
  "green": "en-green.mp3",
  "happy": "en-happy.mp3",
  "water": "en-water.mp3",
  "tiger": "en-tiger.mp3",
  "house": "en-house.mp3",
  "candy": "en-candy.mp3",
  "train": "en-train.mp3",
  "banana": "en-banana.mp3",
  "orange": "en-orange.mp3",
  "bear": "en-bear.mp3",
  "grape": "en-grape.mp3",
  "lemon": "en-lemon.mp3",
  "lion": "en-lion.mp3",
  "peach": "en-peach.mp3",
  "moon": "en-moon.mp3",
  "tree": "en-tree.mp3"
}
